### ISSUE TITLE
How does it work exactly?

### ISSUE THREAD

**Issue by testbot-github** [RayhanADev/Replit-User-Search-v3#4]
Many people don't like to enter their password in some random websites, So if u could explain how it works and why it's safe people will believe it.

**Comment by rayhanadev** [comment]
I can't explain how it works because that's a major security vuln, but I can tell you that the Replit team is "fine" with it.

If you don't want to input your username and password use the `connect.sid` cookie with [this](https://replit-user-search-v3.rayhanadev.repl.co/login?useSid=true) login page.

**Comment by testbot-github** [comment]
> I can't explain how it works because that's a major security vuln, but I can tell you that the Replit team is "fine" with it.
> 
> If you don't want to input your username and password use the `connect.sid` cookie with [this](https://replit-user-search-v3.rayhanadev.repl.co/login?useSid=true) login page.

![image](https://user-images.githubusercontent.com/82745607/136662328-9e46a30e-0414-4303-8ec8-c61563fc5387.png)

**Comment by testbot-github** [comment]
@RayhanADev
